filter:
    paths: [lib/*]
    excluded_paths: [vendor/*, examples/*, tests/*]
checks:
    php: true
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
    external_code_coverage: true